apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert --controller statefulset --volumes persistentVolumeClaim
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: connect
  name: connect
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8083
    - name: "5005"
      port: 5005
      targetPort: 5005
  selector:
    io.kompose.service: connect
  clusterIP: None  
status:
  loadBalancer: {}
--- 
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: connect
  name: connect
spec:
  port:
    targetPort: 8083
  to:
    kind: Service
    name: connect
    weight: 100
  wildcardPolicy: None  
