apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: ./kompose convert --controller daemonset --volumes persistentVolumeClaim
    kompose.version: 1.17.0 (HEAD)
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"StatefulSet","name":"kafka"},{"apiVersion":"apps/v1","kind":"StatefulSet","name":"postgres"}]'
  creationTimestamp: null
  labels:
    io.kompose.service: connect
    app.kubernetes.io/part-of: kafka
  name: connect
spec:
  replicas: 1
  serviceName: connect
  selector:
    matchLabels:
      io.kompose.service: connect
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        io.kompose.service: connect
    spec:
      containers:
        - env:
            - name: BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: CONFIG_STORAGE_TOPIC
              value: my_connect_configs
            - name: GROUP_ID
              value: "1"
            - name: OFFSET_STORAGE_TOPIC
              value: my_connect_offsets
            - name: STATUS_STORAGE_TOPIC
              value: my_source_connect_statuses
          image: debezium-jdbc-es:latest
          name: connect
          ports:
            - containerPort: 8083
            - containerPort: 5005
          resources: {}
      restartPolicy: Always
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
