apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: debezium-jdbc-es
    name: connect
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: debezium/connect:1.0
      from:
        kind: DockerImage
        name: debezium/connect:1.0
      generation: null
      importPolicy: {}
      name: "1.0"
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: debezium-jdbc-es
    name: debezium-jdbc-es
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: debezium-jdbc-es
    name: debezium-jdbc-es
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: debezium-jdbc-es:latest
    postCommit: {}
    resources: {}
    source:
      contextDir: unwrap-smt/debezium-jdbc-es
      git:
        uri: https://github.com/debezium/debezium-examples
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: connect:1.0
      type: Docker
    triggers:
    - github:
        secret: 2ZvAKpVvWJqu1l_7KeCD
      type: GitHub
    - generic:
        secret: Lwi9hSmdrhFENOrHDTOe
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
kind: List
metadata: {}
