apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert --controller statefulset --volumes persistentVolumeClaim
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: mysql
  clusterIP: None  
status:
  loadBalancer: {}
