apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: ./kompose convert --controller daemonset --volumes persistentVolumeClaim
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  serviceName: mysql
  selector:
    matchLabels: 
      io.kompose.service: mysql
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_PASSWORD
              value: mysqlpw
            - name: MYSQL_ROOT_PASSWORD
              value: debezium
            - name: MYSQL_USER
              value: mysqluser
          image: debezium/example-mysql:1.4
          name: mysql
          ports:
            - containerPort: 3306
          resources: {}
      restartPolicy: Always
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
