apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    application: pet-clinic
  name: "pet-clinic-pipeline"
spec:
  source:
    type: Git
    git:
      uri: https://github.com/raffaelespazzoliorg/bdd-demo
      ref: main
  triggers:
    - type: "ConfigChange"
  strategy:
    type: "JenkinsPipeline"
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node("nodejs") {

          stage("Checkout") {
            sh "git clone https://github.com/raffaelespazzoliorg/bdd-demo"   
              dir('bbd-demo')
                {
                sh "ls -ltr"
                }
            
            }

          stage("deploy database") {
            sh "oc apply -f ./bdd-demo/oracle -n poc-dev"
          }  

          stage("service layer") {
            sh "oc apply -f ./bdd-demo/oracle -n poc-dev"
          }

          stage("deploy frontend") {
            sh "oc apply -f ./bdd-demo/spring-pet-clinic-angular -n poc-dev"
          }

          stage("selenium grid") {
            sh "oc apply -f ./bdd-demo/oracle -n poc-dev"
          }

          stage("Run Tests") {
            sh "echo run tests here"
          }
          
        }
