kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: oracle-xe
  labels:
    build: oracle-xe
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'oracle-xe:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'oraclelinux:7-slim'
  postCommit: {}
  source:
    type: Git
    dockerfile: >
      # LICENSE UPL 1.0

      #

      # Copyright (c) 2018, 2020 Oracle and/or its affiliates.

      #

      # ORACLE DOCKERFILES PROJECT

      # --------------------------

      # This is the Dockerfile for Oracle Database 18c Express Edition

      # 

      # REQUIRED FILES TO BUILD THIS IMAGE

      # ----------------------------------

      # None

      #

      # HOW TO BUILD THIS IMAGE

      # -----------------------

      # Run: 

      #      $ docker build -t oracle/database:18.4.0-xe -f Dockerfile.xe .

      #

      #

      # Pull base image

      # ---------------

      FROM oraclelinux:7-slim


      # Labels

      # ------

      LABEL "provider"="Oracle"                                               \
            "issues"="https://github.com/oracle/docker-images/issues"         \
            "volume.data"="/opt/oracle/oradata"                               \
            "volume.setup.location1"="/opt/oracle/scripts/setup"              \
            "volume.setup.location2"="/docker-entrypoint-initdb.d/setup"      \
            "volume.startup.location1"="/opt/oracle/scripts/startup"          \
            "volume.startup.location2"="/docker-entrypoint-initdb.d/startup"  \
            "port.listener"="1521"                                            \
            "port.oemexpress"="5500"                                          \
            "port.apex"="8080"

      # Environment variables required for this build (do NOT change)

      # -------------------------------------------------------------

      ENV ORACLE_BASE=/opt/oracle \
          ORACLE_HOME=/opt/oracle/product/18c/dbhomeXE \
          ORACLE_SID=XE \
          INSTALL_FILE_1="https://download.oracle.com/otn-pub/otn_software/db-express/oracle-database-xe-18c-1.0-1.x86_64.rpm" \
          RUN_FILE="runOracle.sh" \
          PWD_FILE="setPassword.sh" \
          CONF_FILE="oracle-xe-18c.conf" \
          CHECK_SPACE_FILE="checkSpace.sh" \
          CHECK_DB_FILE="checkDBStatus.sh" \
          INSTALL_DIR="$HOME/install" \
          ORACLE_DOCKER_INSTALL="true"

      # Use second ENV so that variable get substituted

      ENV PATH=$ORACLE_HOME/bin:$PATH


      # Copy binaries

      # -------------

      COPY $CHECK_SPACE_FILE $RUN_FILE $PWD_FILE $CHECK_DB_FILE $CONF_FILE
      $INSTALL_DIR/


      RUN chmod ug+x $INSTALL_DIR/*.sh && \
          sync && \
          $INSTALL_DIR/$CHECK_SPACE_FILE && \
          cd $INSTALL_DIR && \
          yum -y install openssl oracle-database-preinstall-18c && \
          sed -i -e 's/\(oracle\s\+hard\s\+nofile\)/# \1/' /etc/security/limits.d/oracle-database-preinstall-18c.conf && \
          yum -y localinstall $INSTALL_FILE_1 && \
          rm -rf /var/cache/yum && \
          rm -rf /var/tmp/yum-* && \
          mkdir -p $ORACLE_BASE/scripts/setup && \
          mkdir $ORACLE_BASE/scripts/startup && \
          ln -s $ORACLE_BASE/scripts /docker-entrypoint-initdb.d && \
          mkdir -p $ORACLE_BASE/oradata /home/oracle && \
          chown -R oracle:oinstall $ORACLE_BASE /home/oracle && \
          mv $INSTALL_DIR/$RUN_FILE $ORACLE_BASE/ && \
          mv $INSTALL_DIR/$PWD_FILE $ORACLE_BASE/ && \
          mv $INSTALL_DIR/$CHECK_DB_FILE $ORACLE_BASE/ && \
          mv $INSTALL_DIR/$CONF_FILE /etc/sysconfig/ && \
          ln -s $ORACLE_BASE/$PWD_FILE / && \
          cd $HOME && \
          rm -rf $INSTALL_DIR && \
          chmod ug+x $ORACLE_BASE/*.sh

      HEALTHCHECK --interval=1m --start-period=5m \
         CMD "$ORACLE_BASE/$CHECK_DB_FILE" >/dev/null || exit 1

      CMD exec $ORACLE_BASE/$RUN_FILE
    git:
      uri: 'https://github.com/oracle/docker-images.git'
    contextDir: OracleDatabase/SingleInstance/dockerfiles/18.4.0
  triggers:
    - type: GitHub
      github:
        secret: t6K0g3pkspMqvHPAAoPd
    - type: Generic
      generic:
        secret: cUNi1E5gpACDMG7A7KtU
    - type: ConfigChange
    - type: ImageChange
      imageChange:
        lastTriggeredImageID: >-
          oraclelinux@sha256:d36feb7289a4f03142a16cfa01529fc4febac02c767aeea34ea5e2cc5c8b5e25
  runPolicy: Serial
--- 
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: oracle-xe
  labels:
    build: oracle-xe
spec:
  lookupPolicy:
    local: false
--- 
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: oraclelinux
  namespace: poc-dev
  labels:
    build: oracle-xe
spec:
  lookupPolicy:
    local: false
  tags:
    - name: 7-slim
      annotations:
        openshift.io/imported-from: 'oraclelinux:7-slim'
      from:
        kind: DockerImage
        name: 'oraclelinux:7-slim'
      generation: 2
      importPolicy: {}
      referencePolicy:
        type: Source


