---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: oracle-xe
  labels:
    app: oracle-xe
    app.kubernetes.io/component: oracle-xe
    app.kubernetes.io/instance: oracle-xe
    app.kubernetes.io/part-of: app
spec:
  replicas: 1
  serviceName: oracle-xe
  selector:
    matchLabels:
      app: oracle-xe
  volumeClaimTemplates:
  - metadata:
      name: oradata
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        app: oracle-xe
    spec:
      serviceAccountName: oracle
      containers:
        - name: oracle-xe
          image: oracle-xe:latest
          env:
            - name: ORACLE_PWD
              value: thisisapassword
          command:
            - /bin/bash
            - -c
            - chmod -R a+xwr /opt/oracle/oradata && exec $ORACLE_BASE/$RUN_FILE
          resources:
            limits:
              cpu: 800m
              memory: 3200Mi
            requests:
              cpu: 500m
              memory: 3Gi
          ports:
            - name: listener
              containerPort: 1521
            - name: oemexpress
              containerPort: 5500
          volumeMounts:
            - name: oradata
              mountPath: /opt/oracle/oradata
---
kind: Service
apiVersion: v1
metadata:
  name: oracle-xe
spec:
  clusterIP: None
  ports:
    - name: listener
      protocol: TCP
      port: 1521
      targetPort: 1521
    - name: oemexpress
      protocol: TCP
      port: 5500
      targetPort: 5500
  selector:
    app: oracle-xe
...
