kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: oracle-xe
  labels:
    build: oracle-xe
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'oracle-xe:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'oraclelinux:7-slim'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/oracle/docker-images.git'
    contextDir: OracleDatabase/SingleInstance/dockerfiles/18.4.0
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile.xe
    type: Docker
  triggers:
    - type: GitHub
      github:
        secret: t6K0g3pkspMqvHPAAoPd
    - type: Generic
      generic:
        secret: cUNi1E5gpACDMG7A7KtU
    - type: ConfigChange
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: oraclelinux:latest
  runPolicy: Serial
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: oracle-xe
  labels:
    build: oracle-xe
spec:
  lookupPolicy:
    local: false
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: oraclelinux
  labels:
    build: oracle-xe
spec:
  lookupPolicy:
    local: false
  tags:
    - name: 7-slim
      annotations:
        openshift.io/imported-from: 'oraclelinux:7-slim'
      from:
        kind: DockerImage
        name: 'oraclelinux:7-slim'
      importPolicy: {}
      referencePolicy:
        type: Source
