apiVersion: v1
items:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: spring-petclinic-angular
        app.kubernetes.io/component: spring-petclinic-angular
        app.kubernetes.io/instance: spring-petclinic-angular
      name: nginx
    spec:
      lookupPolicy:
        local: false
      tags:
        - annotations:
            openshift.io/imported-from: nginx:1.20.0
          from:
            kind: DockerImage
            name: nginx:1.20.0
          generation: null
          importPolicy: {}
          name: 1.20.0
          referencePolicy:
            type: ""
    status:
      dockerImageRepository: ""
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: spring-petclinic-angular
        app.kubernetes.io/component: spring-petclinic-angular
        app.kubernetes.io/instance: spring-petclinic-angular
      name: spring-petclinic-angular
    spec:
      lookupPolicy:
        local: false
    status:
      dockerImageRepository: ""
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: spring-petclinic-angular
        app.kubernetes.io/component: spring-petclinic-angular
        app.kubernetes.io/instance: spring-petclinic-angular
      name: spring-petclinic-angular
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: spring-petclinic-angular:latest
      postCommit: {}
      resources: {}
      source:
        git:
          uri: https://github.com/raffaelespazzoliorg/spring-petclinic-angular
        type: Git
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: nginx:1.20.0
          buildArgs:
            - name: REST_API_URL
              value: "http://spring-petclinic-rest/"
        type: Docker
      triggers:
        - github:
            secret: mcSvizkxSi8G-eCg4D4U
          type: GitHub
        - generic:
            secret: RT2QTirKLig0knMJDCpZ
          type: Generic
        - type: ConfigChange
        - imageChange: {}
          type: ImageChange
    status:
      lastVersion: 0
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"spring-petclinic-angular:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"spring-petclinic-angular\")].image"}]'
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: spring-petclinic-angular
        app.kubernetes.io/component: spring-petclinic-angular
        app.kubernetes.io/instance: spring-petclinic-angular
      name: spring-petclinic-angular
    spec:
      replicas: 1
      selector:
        matchLabels:
          deployment: spring-petclinic-angular
      strategy: {}
      template:
        metadata:
          annotations:
            openshift.io/generated-by: OpenShiftNewApp
          creationTimestamp: null
          labels:
            deployment: spring-petclinic-angular
        spec:
          containers:
            - image: " "
              name: spring-petclinic-angular
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources: {}
    status: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: spring-petclinic-angular
        app.kubernetes.io/component: spring-petclinic-angular
        app.kubernetes.io/instance: spring-petclinic-angular
      name: spring-petclinic-angular
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deployment: spring-petclinic-angular
    status:
      loadBalancer: {}
kind: List
metadata: {}
